#!/bin/bash -e
# Which directory to run from
case=.
if [ "$#" -eq 1 ]; then
    case=$1
elif [ "$#" -gt 1 ]; then
   echo usage: run [casedir]
fi
echo running $case

rm $case/log*
blockMesh -case $case > $case/log.blockMesh
cp $case/0/T.orig $case/0/T
foamPostProcess -case $case -func generateT -time 0 > $case/log.foamPostProcess
rm -rf $case/0.* $case/1.*
foamRun -case $case | tee $case/log

# Calculate errors at the final time
errorNorms $case  0 T 1 T
#------------------------------------------------------------------------------
